# Generated by Django 4.0.6 on 2022-07-10 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterField(
            model_name='product',
            name='availability_date',
            field=models.DateField(blank=True, help_text='Data que o produto vai está disponível', null=True, verbose_name='Disponibilidade'),
        ),
        migrations.AlterField(
            model_name='product',
            name='home_city',
            field=models.CharField(help_text='Cidade de Origem Ex: Monte Sião', max_length=50, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_product',
            field=models.ForeignKey(help_text='Tipo de Produto Ex: Café, laranja..', on_delete=django.db.models.deletion.CASCADE, related_name='product_type', to='products.typeproduct', verbose_name='Tipo'),
        ),
    ]
